# Generated by Django 5.2.3 on 2025-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='classrooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='tutoring_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
